---
# the following top-level key is required
CONFIG_NINJA_OBJECTS:
  # each second-level key identifies a config-ninja object
  example-local:
    # set the location that the object is written to
    dest:
      format: json
      path: /tmp/config-ninja/settings.json

    # run the 'list-dir' task after writing to the destination path
    hooks: [list-dir]

    # specify where the object is stored / retrieved from
    source:
      backend: local
      format: yaml

      init:
        kwargs:
          path: config-ninja-settings.yaml

  example-local-template:
    dest:
      path: /tmp/config-ninja/settings-subset.toml
      format: templates/settings-subset.toml.j2

    source:
      backend: local
      format: yaml

      new:
        kwargs:
          path: config-ninja-settings.yaml

  example-appconfig:
    dest:
      format: raw
      path: /tmp/datadog-agent/datadog.yaml

    source:
      backend: appconfig

      # instantiate the backend class using its 'new()' method
      new:
        kwargs:
          application_name: Hello World 1
          configuration_profile_name: /dev/etc/datadog-agent/datadog.yaml
          environment_name: dev

# task definitions are referenced by 'hooks'
tool.poe:
  tasks:
    list-dir:
      cmd: ls

    print-environ:
      cmd: printenv
