from collections.abc import Mapping
from pathlib import Path

class Virtualenv:
    path: Path
    def __init__(self, path: Path) -> None: ...
    def exists(self) -> bool: ...
    def bin_dir(self) -> Path: ...
    def resolve_executable(self, executable: str) -> str: ...
    @staticmethod
    def detect(parent_dir: Path) -> bool: ...
    def valid(self) -> bool: ...
    def get_env_vars(self, base_env: Mapping[str, str]) -> dict[str, str]: ...
