---
# top-level key for logging settings
CONFIG_NINJA_LOGGING:
  loggers:
    # this example sets a specific logger to the DEBUG level
    tests.acceptance.test_620:
      level: DEBUG
  disable_existing_loggers: false
